import { defineConfig } from "vitest/config";

const slow = process.env.SURVIDLE_TEST_SUITE === "slow";
// Keep integration files that advance the game clock, sweep seeds or exercise
// large frame/stochastic loops out of the per-commit suite. Exact file names
// make the split reviewable; the discovery guard keeps both sides exhaustive.
const slowTestFiles = [
  "tests/advance-save.test.ts",
  "tests/animal-agents.test.ts",
  "tests/animals.test.ts",
  "tests/axes-body.test.ts",
  "tests/bark.test.ts",
  "tests/bedding.test.ts",
  "tests/boat.test.ts",
  "tests/body.test.ts",
  "tests/bodyorder.test.ts",
  "tests/camp.test.ts",
  "tests/carcass.test.ts",
  "tests/card.test.ts",
  "tests/carry.test.ts",
  "tests/churn.test.ts",
  "tests/clothing.test.ts",
  "tests/cues.test.ts",
  "tests/deadwood.test.ts",
  "tests/decay.test.ts",
  "tests/dial.test.ts",
  "tests/eggs.test.ts",
  "tests/embers.test.ts",
  "tests/emberui.test.ts",
  "tests/epitaph.test.ts",
  "tests/events.test.ts",
  "tests/explore.test.ts",
  "tests/face.test.ts",
  "tests/fat.test.ts",
  "tests/fill.test.ts",
  "tests/fire.test.ts",
  "tests/firesite.test.ts",
  "tests/fish.test.ts",
  "tests/forecast.test.ts",
  "tests/forecaster.test.ts",
  "tests/opportunities-deeds.test.ts",
  "tests/opportunities-fire.test.ts",
  "tests/hand.test.ts",
  "tests/hang.test.ts",
  "tests/hone.test.ts",
  "tests/horizon.test.ts",
  "tests/hunger.test.ts",
  "tests/hurry.test.ts",
  "tests/hut.test.ts",
  "tests/ice.test.ts",
  "tests/identity.test.ts",
  "tests/intent.test.ts",
  "tests/ladder.test.ts",
  "tests/landing.test.ts",
  "tests/ledger.test.ts",
  "tests/list.test.ts",
  "tests/needs.test.ts",
  "tests/night-work.test.ts",
  "tests/nobody.test.ts",
  "tests/orderpanel.test.ts",
  "tests/orders.test.ts",
  "tests/pause.test.ts",
  "tests/plants.test.ts",
  "tests/player.test.ts",
  "tests/probe.test.ts",
  "tests/quirks.test.ts",
  "tests/read.test.ts",
  "tests/record.test.ts",
  "tests/reference.test.ts",
  "tests/roots.test.ts",
  "tests/scheduler.test.ts",
  "tests/seep.test.ts",
  "tests/shopping.test.ts",
  "tests/sites.test.ts",
  "tests/siting.test.ts",
  "tests/skills.test.ts",
  "tests/sleep.test.ts",
  "tests/snowshelter.test.ts",
  "tests/spine.test.ts",
  "tests/startday.test.ts",
  "tests/storm.test.ts",
  "tests/survivor-ui.test.ts",
  "tests/tasks.test.ts",
  "tests/teach.test.ts",
  "tests/tools.test.ts",
  "tests/torch.test.ts",
  "tests/trap.test.ts",
  "tests/trough.test.ts",
  "tests/ui.test.ts",
  "tests/voice.test.ts",
  "tests/walkorders.test.ts",
  "tests/water.test.ts",
  "tests/wayfinding.test.ts",
  "tests/wayhome.test.ts",
  "tests/weather.test.ts",
  "tests/wildlife.test.ts",
  "tests/words.test.ts",
  "tests/workday.test.ts",
  "tests/world.test.ts",
  "tests/year.test.ts",
];

export default defineConfig({
  test: {
    environment: "happy-dom",
    setupFiles: ["tests/setup-worlds.ts"],
    include: slow ? ["tests/slow/**/*.test.ts", ...slowTestFiles] : ["tests/**/*.test.ts"],
    exclude: slow ? [] : ["tests/slow/**", ...slowTestFiles],
  },
});
