import type { CardDef } from "../types";

export const VICTORY_CARD_ID = "bindHisHands";

export const PLAYER_CARDS: CardDef[] = [
  {
    id: "wiggleOut",
    name: "Wiggle Out of the Ropes",
    side: "player",
    kind: "offensive",
    tags: [],
    requires: { bound: true },
    effects: [{ kind: "setBound", value: false }],
    rules: "Free yourself from the chair.",
    flavor: "Your father tied better knots than this. You hope.",
    narration: "You work your wrists against the tape.",
  },
  {
    id: "rockTheChair",
    name: "Rock the Chair",
    side: "player",
    kind: "offensive",
    tags: [],
    requires: { bound: true },
    effects: [{ kind: "setToppled", value: true }],
    rules: "Topple yourself. He must spend his next turn hauling you up, ending Near and Off-balance.",
    flavor: "The floor is closer than it looks.",
    narration: "You throw your weight sideways and go over with the chair.",
  },
  {
    id: "headbutt",
    name: "Headbutt",
    side: "player",
    kind: "offensive",
    tags: ["physical"],
    requires: { range: "near", convictDistractedOrOffBalance: true },
    effects: [{ kind: "damage", target: "convict", amount: 3 }],
    rules: "He must be Near and either Distracted or Off-balance. Deal 3 Vigor. Legal even while Bound.",
    flavor: "No wind-up. Just bone.",
    narration: "You snap your forehead into his face.",
  },
  {
    id: "kickHisKnee",
    name: "Kick His Knee",
    side: "player",
    kind: "offensive",
    tags: ["physical"],
    requires: { bound: false, range: "near" },
    effects: [
      { kind: "damage", target: "convict", amount: 3 },
      { kind: "setOffBalance", value: true },
    ],
    rules: "Deal 3 Vigor and knock him Off-balance.",
    flavor: "Knees do not care how big you are.",
    narration: "You drive your heel into the side of his knee.",
  },
  {
    id: "shoulderCharge",
    name: "Shoulder Charge",
    side: "player",
    kind: "offensive",
    tags: ["physical"],
    requires: { bound: false, range: "near" },
    effects: [{ kind: "damage", target: "convict", amount: 2, offBalanceBonus: 3 }],
    rules: "Deal 2 Vigor, or 5 if he is Off-balance, which consumes it.",
    flavor: "Everything you have, all at once.",
    narration: "You put your shoulder through his chest.",
  },
  {
    id: "grabForTheKnife",
    name: "Grab for the Knife",
    side: "player",
    kind: "offensive",
    tags: ["physical"],
    requires: {
      bound: false,
      range: "near",
      convictWeaponDown: false,
      convictDistractedOrOffBalance: true,
    },
    effects: [{ kind: "setWeaponDown", value: true }],
    rules: "He must be Near and either Distracted or Off-balance. His knife hits the floor.",
    flavor: "You will think about the cut on your palm later.",
    narration: "You close your hand around the blade and twist.",
  },
  {
    id: "stallHim",
    name: "Stall Him With Questions",
    side: "player",
    kind: "offensive",
    tags: ["deception"],
    requires: {},
    effects: [{ kind: "willpower", target: "convict", amount: -2 }],
    rules: "Always legal. His Willpower -2.",
    flavor: "Keep him talking. Talking is not cutting.",
    narration: "You ask him how long he has been out.",
  },
  {
    id: "lieAboutTheMoney",
    name: "Lie About the Money",
    side: "player",
    kind: "offensive",
    tags: ["deception"],
    requires: {},
    effects: [
      { kind: "setDistracted", turns: 2 },
      { kind: "setRange", value: "away" },
    ],
    rules: "He goes to check. Distracted 2, and he moves Away.",
    flavor: "The best lies are the boring ones.",
    narration: "You tell him about the strongbox in the garage.",
  },
  {
    id: "lampCord",
    name: "Lamp Cord",
    side: "player",
    kind: "offensive",
    tags: ["physical"],
    requires: { zone: "bedroom", bound: false, range: "near" },
    effects: [
      { kind: "damage", target: "convict", amount: 3 },
      { kind: "setOffBalance", value: true },
    ],
    rules: "Bedroom only. Deal 3 Vigor and knock him Off-balance.",
    flavor: "Her reading lamp. She never turns it off.",
    narration: "You loop the cord around his ankle and pull.",
  },
  {
    id: "thePhoneRings",
    name: "The Phone Rings",
    side: "player",
    kind: "offensive",
    tags: ["event"],
    requires: {},
    effects: [{ kind: "setDistracted", turns: 2 }],
    rules: "Always legal. He goes Distracted 2. Does not move him.",
    flavor: "The machine picks up in your voice, cheerful, from before.",
    narration: "The phone starts ringing in the hall.",
  },
  {
    id: "headlightsInTheWindow",
    name: "Headlights in the Window",
    side: "player",
    kind: "offensive",
    tags: ["event"],
    requires: {},
    effects: [
      { kind: "setDistracted", turns: 1 },
      { kind: "willpower", target: "convict", amount: -2 },
    ],
    rules: "Always legal. He goes Distracted 1. His Willpower -2. Does not move him.",
    flavor: "A car turning around in the driveway. He does not know that.",
    narration: "Headlights sweep across the curtains and are gone.",
  },
  {
    id: "theDogNextDoor",
    name: "The Dog Next Door",
    side: "player",
    kind: "offensive",
    tags: ["event"],
    requires: {},
    effects: [{ kind: "setDistracted", turns: 1 }],
    rules: "Always legal. He goes Distracted 1. Does not move him.",
    flavor: "It has never once stopped on its own.",
    narration: "The neighbor's dog starts barking and will not stop.",
  },
  {
    id: "stoic",
    name: "Stoic",
    side: "player",
    kind: "defensive",
    tags: [],
    requires: {},
    effects: [{ kind: "willpower", target: "player", amount: 2 }],
    rules: "Answer anything. Your Willpower +2, applied before his card resolves.",
    flavor: "You have been afraid before. This is only louder.",
    narration: "You let your face go flat and give him nothing.",
  },
  {
    id: "takeItForHer",
    name: "Take It For Her",
    side: "player",
    kind: "defensive",
    tags: [],
    requires: { answersTag: "threatensWife" },
    effects: [{ kind: "interposeForWife", selfDamage: 2 }],
    rules: "Answer a card that threatens her. She takes nothing. You take 2 Vigor.",
    flavor: "You get between them. It is the only thing you are sure of.",
    narration: "You put yourself between him and her.",
  },
  {
    id: "flinch",
    name: "Flinch",
    side: "player",
    kind: "defensive",
    tags: [],
    requires: { answersDamageToOwner: true },
    effects: [{ kind: "halveIncomingDamage" }],
    rules: "Answer a card that hurts you. Halve its Vigor damage, rounded up.",
    flavor: "Your body decides before you do.",
    narration: "You turn with it at the last moment.",
  },
  {
    id: "talkHimDown",
    name: "Talk Him Down",
    side: "player",
    kind: "defensive",
    tags: [],
    requires: { answersCoercion: true },
    effects: [{ kind: "stripCoercion" }],
    rules: "Answer a threat. Its demand is cancelled. Its damage still lands.",
    flavor: "Name him. People find it harder to hurt someone who knows them.",
    narration: "You say his name out loud, slowly.",
  },
  {
    id: "secretFreezer",
    name: "\"There's a jar in the freezer.\"",
    side: "player",
    kind: "defensive",
    tags: ["secret", "fixture"],
    requires: {},
    effects: [
      { kind: "negateLead" },
      { kind: "restoreWillpowerTo", target: "player", value: 3 },
      { kind: "setRange", value: "away" },
      { kind: "setDistracted", turns: 2 },
    ],
    rules: "Secret 1 of 3. Blocks his card. Your Willpower becomes 3. He goes to the kitchen: Away, Distracted 2.",
    flavor: "Four hundred dollars in a jam jar. Grocery money.",
    narration: "You tell him about the freezer.",
  },
  {
    id: "secretSafe",
    name: "\"The safe is behind the headboard.\"",
    side: "player",
    kind: "defensive",
    tags: ["secret", "fixture"],
    requires: {},
    effects: [
      { kind: "negateLead" },
      { kind: "restoreWillpowerTo", target: "player", value: 3 },
      { kind: "setZone", value: "bedroom" },
      { kind: "setRange", value: "near" },
      { kind: "setOffBalance", value: true },
    ],
    rules: "Secret 2 of 3. Blocks his card. Your Willpower becomes 3. The scene moves to the bedroom and he is Off-balance clawing at the wall.",
    flavor: "It has your passports in it. And almost nothing else.",
    narration: "You tell him about the safe.",
  },
  {
    id: "secretFloorboard",
    name: "\"It's under the floorboard in the nursery.\"",
    side: "player",
    kind: "defensive",
    tags: ["secret", "fixture"],
    requires: {},
    effects: [{ kind: "loseRun" }],
    rules: "Secret 3 of 3. He has what he came for. You lose.",
    flavor: "You never should have kept it in the house.",
    narration: "You tell him about the nursery.",
  },
  {
    id: VICTORY_CARD_ID,
    name: "Bind His Hands",
    side: "player",
    kind: "offensive",
    tags: ["fixture"],
    requires: { convictIncapacitated: true },
    effects: [],
    rules: "Only against an Incapacitated convict. Ends the run in your favour.",
    flavor: "The same tape. There is plenty left.",
    narration: "You get his wrists behind him and start wrapping.",
  },
];

export const SECRETS: string[] = ["secretFreezer", "secretSafe", "secretFloorboard"];

export const PLAYER_DECK: string[] = [
  "wiggleOut",
  "rockTheChair",
  "headbutt",
  "kickHisKnee",
  "shoulderCharge",
  "grabForTheKnife",
  "stallHim",
  "stallHim",
  "lieAboutTheMoney",
  "lampCord",
  "thePhoneRings",
  "headlightsInTheWindow",
  "theDogNextDoor",
  "stoic",
  "stoic",
  "takeItForHer",
  "flinch",
  "flinch",
  "talkHimDown",
];
