import type { CardDef } from "../types";

export const NOT_YET_ID = "notYet";

export const CONVICT_CARDS: CardDef[] = [
  {
    id: "backhand",
    name: "Backhand",
    side: "convict",
    kind: "offensive",
    tags: ["physical"],
    requires: { range: "near" },
    effects: [
      { kind: "damage", target: "player", amount: 1 },
      { kind: "willpower", target: "player", amount: -1 },
    ],
    rules: "He must be Near. Your Vigor -1, your Willpower -1.",
    flavor: "Almost casual. That is the worst part.",
    narration: "He backhands you across the mouth.",
  },
  {
    id: "buttOfTheKnife",
    name: "Butt of the Knife",
    side: "convict",
    kind: "offensive",
    tags: ["physical"],
    requires: { range: "near", convictWeaponDown: false },
    effects: [{ kind: "damage", target: "player", amount: 3 }],
    rules: "He must be Near and armed. Your Vigor -3.",
    flavor: "He does not even turn the blade around.",
    narration: "He clubs you with the handle.",
  },
  {
    id: "whereIsIt",
    name: "Where Is It?",
    side: "convict",
    kind: "offensive",
    tags: [],
    requires: {},
    coercion: true,
    effects: [
      { kind: "setRange", value: "near" },
      { kind: "willpower", target: "player", amount: -2 },
    ],
    rules: "He crosses the room to you. He ends Near. Your Willpower -2. If your Willpower is 0 afterwards, you must give up a secret.",
    flavor: "He asks it the same way every time. That is the pressure.",
    narration: "He closes the distance and asks where it is.",
  },
  {
    id: "knifeToHerThroat",
    name: "Knife to Her Throat",
    side: "convict",
    kind: "offensive",
    tags: ["threatensWife"],
    requires: { convictWeaponDown: false },
    coercion: true,
    effects: [{ kind: "willpower", target: "player", amount: -3 }],
    rules: "He must be armed. Your Willpower -3. If your Willpower is 0 afterwards, you must give up a secret.",
    flavor: "She does not scream. That is somehow worse.",
    narration: "He puts the edge against her neck.",
  },
  {
    id: "breakHerFingers",
    name: "Break Her Fingers",
    side: "convict",
    kind: "offensive",
    tags: ["threatensWife"],
    requires: { coercionDefused: true },
    effects: [{ kind: "damage", target: "wife", amount: 2 }],
    rules: "Only once you have defused a threat. Her Vigor -2, and Bond costs you Willpower -4.",
    flavor: "He wanted you to believe him. Now you do.",
    narration: "He bends her hand back until something gives.",
  },
  {
    id: "tightenTheRopes",
    name: "Tighten the Ropes",
    side: "convict",
    kind: "offensive",
    tags: [],
    requires: { range: "near" },
    effects: [{ kind: "bindOrHurt", amount: 1 }],
    rules: "He must be Near. If you are free he binds you again. Otherwise your Vigor -1.",
    flavor: "He does not look at you while he does it.",
    narration: "He wrenches the tape tighter.",
  },
  {
    id: "ransackTheRoom",
    name: "Ransack the Room",
    side: "convict",
    kind: "offensive",
    tags: [],
    requires: {},
    effects: [
      { kind: "setRange", value: "away" },
      { kind: "setDistracted", turns: 1 },
      { kind: "willpower", target: "player", amount: -2 },
    ],
    rules: "He searches. He moves Away and is Distracted 1, but your Willpower -2.",
    flavor: "Your drawers. Her drawers. The children's.",
    narration: "He starts pulling drawers onto the floor.",
  },
  {
    id: "dragYouToTheBedroom",
    name: "Drag You to the Bedroom",
    side: "convict",
    kind: "offensive",
    tags: [],
    requires: { zone: "livingRoom" },
    effects: [
      { kind: "setZone", value: "bedroom" },
      { kind: "setRange", value: "near" },
      { kind: "damage", target: "player", amount: 1 },
    ],
    rules: "Living room only. The scene moves to the bedroom, he ends Near, your Vigor -1.",
    flavor: "The chair legs leave marks on the hallway floor.",
    narration: "He drags you, chair and all, down the hall.",
  },
  {
    id: "snatchItBack",
    name: "Snatch It Back",
    side: "convict",
    kind: "offensive",
    tags: [],
    requires: { convictWeaponDown: true },
    effects: [
      { kind: "setWeaponDown", value: false },
      { kind: "willpower", target: "player", amount: -1 },
    ],
    rules: "Only while his knife is down. He picks it up. Your Willpower -1.",
    flavor: "You had it for four seconds.",
    narration: "He scoops the knife off the floor.",
  },
  {
    id: "expertKnots",
    name: "Expert Knots",
    side: "convict",
    kind: "defensive",
    tags: [],
    requires: { answersCardId: "wiggleOut" },
    effects: [
      { kind: "negateLead" },
      { kind: "damage", target: "player", amount: 1 },
    ],
    rules: "Answers Wiggle Out of the Ropes. It fails and your Vigor -1.",
    flavor: "Eleven years is a long time to practise.",
    narration: "He watches your wrists and laughs.",
  },
  {
    id: "brace",
    name: "Brace",
    side: "convict",
    kind: "defensive",
    tags: [],
    requires: { convictDistracted: false, answersDamageToConvictAtLeast: 1 },
    effects: [{ kind: "negateLead" }],
    rules: "He must not be Distracted. Answers a card that would hurt him. It does nothing.",
    flavor: "He saw it coming from the moment you shifted your weight.",
    narration: "He turns his shoulder into it.",
  },
  {
    id: "heardThatBefore",
    name: "I've Heard That Before",
    side: "convict",
    kind: "defensive",
    tags: [],
    requires: { answersTag: "deception" },
    effects: [
      { kind: "negateLead" },
      { kind: "willpower", target: "player", amount: -2 },
    ],
    rules: "Answers a deception. It fails and your Willpower -2.",
    flavor: "Everyone in here has a garage.",
    narration: "He tells you he has heard that one before.",
  },
  {
    id: NOT_YET_ID,
    name: "Not Yet",
    side: "convict",
    kind: "defensive",
    tags: ["fixture"],
    requires: { answersCardId: "bindHisHands" },
    effects: [{ kind: "reviveConvict", vigor: 3 }],
    rules: "Once per run. Answers Bind His Hands. He surges back up to 3 Vigor and is no longer Incapacitated.",
    flavor: "His eyes were open the whole time.",
    narration: "His hand closes on your wrist.",
  },
];

export const CONVICT_DECK: string[] = [
  "backhand",
  "backhand",
  "buttOfTheKnife",
  "whereIsIt",
  "whereIsIt",
  "knifeToHerThroat",
  "breakHerFingers",
  "tightenTheRopes",
  "ransackTheRoom",
  "dragYouToTheBedroom",
  "snatchItBack",
  "expertKnots",
  "brace",
  "brace",
  "heardThatBefore",
];
