/**
 * The sync code's vocabulary: 1024 short, ordinary words, so three of them
 * carry thirty bits and read aloud over a shoulder. Nothing here is a
 * proper noun or a word that would embarrass a player to say. Generated
 * once from a hand-written list, deduplicated, and never reordered: a
 * code is three indexes into this array, so a word moved is a world lost.
 *
 * `tests/sync-code.test.ts` holds the count, the uniqueness and the shape.
 */
export const WORDS: readonly string[] = [
  "abbey", "acre", "adze", "aim", "ale", "alley", "anchor", "ancient", "angelica", "ankle", "ant", "antler", "apple", "april", "arm", "arrow",
  "ash", "auk", "aunt", "autumn", "awl", "axe", "axle", "baby", "back", "bacon", "bag", "bald", "band", "bar", "bard", "bare",
  "barn", "barrel", "barter", "basket", "bat", "beach", "beam", "bean", "bear", "beat", "beck", "bed", "bee", "beet", "beetle", "bell",
  "bellows", "belly", "bench", "bilberry", "bind", "biscuit", "bitter", "bland", "blanket", "bleat", "blend", "blessed", "blood", "blunt", "board", "boat",
  "bog", "boil", "boletus", "bone", "borrow", "boulder", "box", "boy", "brake", "bramble", "bran", "branch", "brass", "brave", "bread", "bream",
  "breast", "brew", "brewer", "bridle", "bright", "brim", "brine", "brisk", "brittle", "broad", "bronze", "brook", "broth", "brother", "brow", "brown",
  "brush", "buckle", "build", "buoy", "burbot", "burdock", "burrow", "busy", "butler", "butter", "buy", "buzz", "cabbage", "cabin", "cage", "cake",
  "calf", "call", "calm", "campion", "canny", "canyon", "captain", "caraway", "carrot", "carry", "cart", "carve", "cascade", "cask", "castle", "catkin",
  "cave", "chaff", "chain", "chair", "char", "chart", "chat", "cheek", "cheese", "cherry", "chest", "chestnut", "chief", "chimney", "chin", "chirp",
  "chive", "chop", "cider", "cinder", "city", "clad", "clam", "clan", "clap", "claw", "clay", "clearing", "clever", "cliff", "climb", "cloaked",
  "close", "cloth", "clover", "cluck", "clutch", "coal", "coast", "cobalt", "cobbler", "cod", "coil", "coin", "col", "cold", "comet", "compass",
  "cone", "coo", "cool", "copse", "cord", "corner", "cottage", "court", "cousin", "cove", "cowberry", "crab", "cradle", "crag", "crane", "crate",
  "crawl", "creek", "creel", "creep", "croft", "cross", "crow", "crown", "crush", "crust", "cuckoo", "cup", "cure", "cursed", "cyan", "daisy",
  "dale", "dam", "damp", "dance", "dark", "darn", "dash", "daughter", "dawn", "deep", "deer", "delta", "den", "dial", "dill", "dim",
  "dipper", "ditch", "dive", "diver", "doctor", "dolphin", "door", "double", "dough", "drag", "draw", "dream", "drift", "drill", "drip", "drive",
  "drop", "drought", "drum", "dry", "duck", "dune", "dunlin", "dusk", "dwarf", "eagle", "ear", "earth", "ebony", "echo", "edge", "eel",
  "egg", "elder", "elf", "elk", "ember", "emerald", "empty", "equinox", "ermine", "estuary", "evening", "faint", "fair", "falls", "fancy", "far",
  "farm", "fast", "fat", "father", "feather", "felt", "fen", "fence", "fennel", "fern", "fiddle", "field", "fierce", "finch", "fine", "finger",
  "fir", "fire", "firm", "first", "fizz", "flame", "flash", "flat", "flee", "fling", "flint", "float", "flour", "flute", "fly", "foam",
  "fold", "foot", "ford", "forest", "forge", "fort", "fox", "foxglove", "free", "fresh", "friend", "frog", "frost", "fry", "full", "fur",
  "furry", "gale", "garden", "gate", "gather", "gauge", "gaze", "gentle", "ghost", "giant", "girl", "give", "glad", "glade", "glen", "glow",
  "gnat", "godwit", "gorge", "granite", "grass", "gravel", "grayling", "grease", "grebe", "greet", "griddle", "grill", "grim", "grin", "grind", "grip",
  "grouse", "growl", "gruel", "guard", "guide", "gull", "gust", "gypsy", "hair", "hairy", "half", "hammer", "hang", "harbour", "hare", "harrier",
  "harvest", "hawk", "hawthorn", "hay", "haze", "hazel", "hazelnut", "head", "healer", "heat", "heath", "heather", "heave", "heavy", "hedgehog", "heel",
  "hem", "hero", "heron", "herring", "hew", "hidden", "hide", "high", "hill", "hip", "hiss", "hit", "hoe", "hoist", "hold", "hollow",
  "holly", "holy", "honey", "honk", "hooded", "hoop", "hop", "horn", "hornet", "hour", "howl", "hull", "hum", "hunt", "hunter", "hurry",
  "husband", "hush", "hut", "ice", "idle", "indigo", "inlet", "inn", "iron", "island", "isle", "islet", "ivory", "ivy", "jackdaw", "jam",
  "jar", "jaw", "jay", "jet", "joint", "judge", "jug", "july", "june", "juniper", "kale", "kayak", "keel", "keep", "keeper", "keg",
  "kernel", "kestrel", "kick", "kin", "kind", "kite", "knee", "kneel", "knife", "knight", "knit", "knock", "knot", "knuckle", "lad", "ladle",
  "lair", "lake", "lamp", "lamprey", "land", "lane", "lapwing", "larch", "lark", "lash", "lass", "last", "late", "laugh", "launch", "lawn",
  "lazy", "lead", "leaf", "league", "lean", "leather", "leave", "ledge", "leek", "leg", "lemming", "lemon", "lend", "lichen", "lie", "light",
  "lilac", "lily", "lime", "line", "linen", "ling", "linger", "lingon", "linnet", "liver", "loaf", "loam", "loch", "lock", "lodge", "log",
  "long", "look", "loop", "lord", "loud", "low", "lucky", "lye", "lynx", "maid", "mallard", "man", "manor", "map", "maple", "march",
  "mark", "marsh", "marten", "martin", "mash", "masked", "mason", "mat", "mauve", "meadow", "meal", "meek", "meet", "mellow", "melt", "mend",
  "merchant", "merry", "midge", "midnight", "midwife", "mile", "milk", "miller", "mink", "minnow", "mint", "minute", "mire", "mite", "mix", "mole",
  "monk", "moo", "moon", "moor", "moose", "morel", "moss", "moth", "mother", "mount", "mouth", "mud", "mug", "mushroom", "mussel", "myth",
  "naked", "narrow", "navy", "near", "neck", "needle", "nerve", "ness", "nest", "nettle", "new", "newt", "next", "night", "nightjar", "nod",
  "noon", "nose", "note", "nudge", "nurse", "nuthatch", "oak", "oar", "oat", "ocean", "ochre", "oil", "old", "onion", "open", "orange",
  "orchard", "orchid", "ounce", "oven", "owl", "pack", "paddle", "pail", "paint", "pale", "palm", "pan", "parsley", "pass", "pasture", "path",
  "pea", "peat", "pebble", "peer", "peg", "pelt", "penny", "petal", "pier", "pigeon", "pike", "pillow", "pin", "pine", "pink", "pipe",
  "pipit", "pirate", "pitch", "plain", "plank", "plant", "plateau", "play", "plum", "plump", "poet", "point", "pole", "pollen", "pond", "pool",
  "poor", "poplar", "poppy", "porpoise", "port", "post", "pot", "potter", "pouch", "pound", "press", "primrose", "proud", "puffball", "pull", "punch",
  "punt", "purple", "purr", "push", "quack", "quartz", "quay", "queen", "quick", "quiet", "quill", "quilt", "quiver", "race", "raft", "raider",
  "raise", "rake", "rap", "rapid", "rasp", "raven", "raw", "red", "redpoll", "redshank", "redstart", "reed", "reef", "reeve", "rein", "reindeer",
  "resin", "rest", "rhyme", "rich", "ride", "ridge", "rill", "rim", "ripe", "ripple", "rise", "river", "road", "roast", "roll", "roof",
  "roost", "root", "rope", "rose", "round", "route", "row", "rowan", "ruby", "rudder", "rug", "ruler", "rune", "rung", "rush", "rye",
  "sack", "sacred", "sad", "saddle", "saga", "sage", "sail", "sallow", "salmon", "salt", "salty", "sand", "sap", "sausage", "save", "saw",
  "scarlet", "scribe", "scrub", "seal", "season", "sedge", "see", "seed", "seer", "sell", "set", "shade", "shallow", "sharp", "shed", "shelf",
  "shell", "shilling", "shin", "shingle", "shoal", "shod", "shoot", "shore", "short", "shoulder", "shout", "shove", "shrew", "shrimp", "shut", "shy",
  "silt", "sing", "single", "sister", "skald", "skate", "skerry", "ski", "skiff", "skin", "skull", "sky", "slack", "sled", "sledge", "sleet",
  "slide", "slim", "slip", "slope", "small", "smelt", "smile", "smith", "smoke", "smooth", "snail", "snap", "snare", "sneak", "snipe", "sod",
  "soil", "sole", "solemn", "son", "song", "soot", "sorrel", "source", "sow", "spark", "spend", "spicy", "spider", "spine", "spirit", "splash",
  "splice", "split", "spoon", "spot", "sprat", "spray", "spring", "sprite", "spruce", "spy", "squall", "square", "squire", "squirrel", "stake", "stalk",
  "stand", "star", "stare", "starling", "stay", "steak", "steel", "steep", "stew", "steward", "stile", "still", "stir", "stoat", "stool", "stoop",
  "store", "stork", "storm", "stout", "strand", "strap", "straw", "stream", "street", "strike", "string", "stump", "sugar", "sun", "sunset", "sure",
  "surf", "swallow", "swamp", "swan", "sweep", "swim", "tailor", "take", "tale", "tall", "tallow", "tanner", "tansy", "tap", "tar", "tarn",
  "taut", "tavern", "teal", "tender", "tent", "tern", "tether", "thane", "thaw", "thick", "thigh", "thin", "thistle", "thorn", "throat", "thrush",
  "thumb", "thunder", "thyme", "tie", "tight", "till", "tin", "tinker", "toad", "today", "toe", "token", "tongs", "tooth", "torch", "toss",
  "tough", "tow", "tower", "town", "track", "trail", "trap", "trench", "tribe", "trill", "triple", "troll", "trough", "trout", "true", "trunk",
  "tub", "tune", "turf", "turn", "turnip", "twilight", "twin", "twine", "twist", "uncle", "vale", "verse", "vetch", "viking", "village", "vinegar",
  "vineyard", "violet", "vivid", "wade", "wagon", "wagtail", "waist", "wait", "walk", "wall", "walnut", "warbler", "warden", "warm", "wash", "wasp",
  "watch", "wave", "wax", "waxwing", "way", "weaver", "web", "wedge", "week", "weep", "weir", "whale", "wheat", "wheel", "whey", "whirl",
  "whistle", "white", "whittle", "wick", "wife", "wigeon", "willow", "window", "wine", "winter", "wise", "wizard", "wolf", "woman", "wood", "wool",
  "worm", "wrap", "wren", "wring", "wrist", "wryneck", "yard", "yarn", "yarrow", "year", "yellow", "yelp", "yew", "yoke", "yolk", "young",
];
